spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id:
            client-secret:
            redirect-uri: http://localhost:8000/login/oauth2/code/google
            scope:
              - profile
              - email
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: sub

mybatis:
  mapper-locations: classpath:mappers/*.xml
  config-location: classpath:mybatis-config.xml
  driver-class-name: org.postgresql.Driver
  url: jdbc:postgresql://127.0.0.1:5432/news_db
  username:
  password:
  test-while-idle: true
  time-between-eviction-runs-millis: 60000
  validation-query: SELECT 1
  max-total: 10
  max-idle: 5

server:
  port: 8000